FROM python:3.12-slim

ARG TORCH_VERSION=2.7.0
ARG TORCH_INDEX_URL=https://download.pytorch.org/whl/cu126
ARG PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_INDEX_URL=${PIP_INDEX_URL}

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        git \
        libgl1 \
        libglib2.0-0 \
        pkg-config \
        libcairo2-dev \
        libffi-dev \
    && rm -rf /var/lib/apt/lists/*



WORKDIR /app

RUN python -m pip install --upgrade pip

# 安装 torch
RUN pip install \
        torch==${TORCH_VERSION} \
        torchvision \
        torchaudio \
        --index-url ${TORCH_INDEX_URL}

# 先装 requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

# 复制整个项目
COPY . .

# 关键步骤：安装 sam3 为 editable 包
RUN pip install -e sam3

# EXPOSE 8000

CMD ["bash"]
